Revert "Remove SumInto calls where only InsertInto should be needed."
This reverts commit b521015f706771b3d716361f1076bee661555355.

This commit caused a bug here:

 Error: factorization returned value -22 on level 2
 (in HYMLS_SchurPreconditioner.C, line 602)

git-svn-id: https://vcs.service.rug.nl/svn/fredwubs/hymls@1076 5bcbc087-4b5e-4533-96d0-4097f40ffae9